name: WFB-ng package builder

on:
  push:
    branches: [ master, release-23.08 ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        docker-images:
          - "2023-02-21-raspios-bullseye-armhf-lite"
          - "2023-02-21-raspios-bullseye-arm64-lite"
          - "armbian_23.02.2_nanopineo_jammy_current_5.15.93"
          - "armbian_23.02.1_nanopineo2_jammy_current_5.15.93"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build package
        run: |
          curl -s -L https://github.com/svpcom/wfb-ng/releases/download/wifibroadcast-17.10/qemu-7.2.0-fixed.tar.gz | sudo tar xzv -C /
          make deb_docker DOCKER_SRC_IMAGE=p2ptech/cross-build:${{ matrix.docker-images }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wfb-ng-${{ github.ref_name }}-${{ matrix.docker-images }}
          path: |
            deb_dist/*.deb
